# redis-cluster/templates/statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-cluster.fullname" . }}
spec:
  serviceName: "{{ .Release.Name }}-redis"
  replicas: {{ .Values.redis.cluster.replicas }}
  selector:
    matchLabels:
      app: {{ include "redis-cluster.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ include "redis-cluster.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-cluster.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["{{ .Values.redis.persistence.accessMode }}"]
        storageClassName: "{{ .Values.redis.persistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}

